# Generated by Django 6.0.6 on 2026-07-17 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_principal', models.CharField(max_length=50, verbose_name='Ticket Principal')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineamientos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Lineamiento',
                'verbose_name_plural': 'Lineamientos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LineamientoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('software', 'Software'), ('bdd', 'Base de Datos'), ('infraestructura', 'Capacidad')], max_length=20, verbose_name='Tipo')),
                ('ticket_interno', models.CharField(max_length=50, verbose_name='Ticket Interno')),
                ('lineamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.lineamiento', verbose_name='Lineamiento')),
                ('usuario_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineamientos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado')),
            ],
            options={
                'verbose_name': 'Detalle de Lineamiento',
                'verbose_name_plural': 'Detalles de Lineamiento',
                'unique_together': {('lineamiento', 'tipo')},
            },
        ),
    ]
