# Generated by Django 6.0.6 on 2026-07-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('necesidad', models.CharField(max_length=300, verbose_name='Necesidad')),
                ('lineamiento', models.TextField(verbose_name='Lineamiento')),
                ('mecanismo', models.TextField(verbose_name='Mecanismo de Implementacion')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observacion')),
            ],
            options={
                'verbose_name': 'Lineamiento de Software',
                'verbose_name_plural': 'Lineamientos de Software',
                'ordering': ['id'],
            },
        ),
    ]
