# Generated by Django 6.0.6 on 2026-07-21 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_guideline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineamientodetalle',
            name='lineamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.lineamiento'),
        ),
        migrations.AlterField(
            model_name='lineamientodetalle',
            name='ticket_interno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lineamientodetalle',
            name='tipo',
            field=models.CharField(choices=[('software', 'Software'), ('bdd', 'Base de Datos'), ('infraestructura', 'Capacidad')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lineamientodetalle',
            name='usuario_asignado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineamientos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LineamientoGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.DecimalField(decimal_places=1, default=1.0, max_digits=4, verbose_name='Version')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineamientos_generados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generados', to='core.lineamientodetalle', verbose_name='Detalle')),
            ],
            options={
                'verbose_name': 'Lineamiento Generado',
                'verbose_name_plural': 'Lineamientos Generados',
                'ordering': ['-version'],
                'unique_together': {('detalle', 'version')},
            },
        ),
        migrations.CreateModel(
            name='LineamientoGeneradoFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('necesidad', models.TextField(blank=True)),
                ('lineamiento', models.TextField(blank=True)),
                ('mecanismo', models.TextField(blank=True)),
                ('observacion', models.TextField(blank=True)),
                ('generado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas', to='core.lineamientogenerado')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
