# Generated by Django 6.0.6 on 2026-07-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_lineamientodetalle_lineamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineamientogenerado',
            name='ticket',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Ticket de version'),
        ),
    ]
