# Generated by Django 6.0.6 on 2026-07-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lineamientogenerado_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineamientogenerado',
            name='bdd_schema',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Schema BDD'),
        ),
        migrations.AddField(
            model_name='lineamientogenerado',
            name='bdd_sequences',
            field=models.JSONField(blank=True, null=True, verbose_name='Secuencias BDD'),
        ),
        migrations.AddField(
            model_name='lineamientogenerado',
            name='bdd_sql',
            field=models.TextField(blank=True, default='', verbose_name='SQL guardado'),
        ),
        migrations.AddField(
            model_name='lineamientogenerado',
            name='bdd_tables',
            field=models.JSONField(blank=True, null=True, verbose_name='Tablas BDD'),
        ),
    ]
