# Generated by Django 6.0.6 on 2026-07-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lineamientogenerado_bdd_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineamientodetalle',
            name='diagrama_personalizado',
            field=models.ImageField(blank=True, null=True, upload_to='diagramas_bdd/', verbose_name='Diagrama ER personalizado'),
        ),
    ]
