# Generated by Django 6.0.6 on 2026-07-29 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lineamientodetalle_diagrama_personalizado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_map', models.JSONField(help_text='Mapa {detalle_id: generado_id} usado exactamente al momento de formalizar', verbose_name='Versiones formalizadas')),
                ('documento', models.FileField(upload_to='formalizaciones/', verbose_name='PDF consolidado')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Firma/Revisión'), ('firmado', 'Firmado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formalizaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('lineamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formalizaciones', to='core.lineamiento', verbose_name='Lineamiento (Ticket Padre)')),
            ],
            options={
                'verbose_name': 'Formalización',
                'verbose_name_plural': 'Formalizaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
