# Generated by Django 6.0.6 on 2026-07-29 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_formalizacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formalizacion',
            name='estado',
        ),
        migrations.CreateModel(
            name='FormalizacionFirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmado', models.BooleanField(default=False)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formalizacion_firmas', to='core.lineamientodetalle', verbose_name='Detalle (tipo) que requiere firma')),
                ('formalizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas', to='core.formalizacion')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas_formalizacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Firma de Formalización',
                'verbose_name_plural': 'Firmas de Formalización',
                'unique_together': {('formalizacion', 'detalle')},
            },
        ),
    ]
