# Generated by Django 6.0.6 on 2026-07-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_formalizacion_estado_formalizacionfirma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guideline',
            options={'ordering': ['id'], 'verbose_name': 'Base de Conocimiento', 'verbose_name_plural': 'Base de Conocimiento'},
        ),
        migrations.AddField(
            model_name='guideline',
            name='tipo',
            field=models.CharField(choices=[('SW', 'Software'), ('BDD', 'Base de Datos'), ('INF', 'Infraestructura')], default='SW', max_length=3, verbose_name='Tipo'),
        ),
        migrations.AlterModelTable(
            name='guideline',
            table='Base_Conocimiento',
        ),
        migrations.AlterModelTable(
            name='lineamiento',
            table='Lineamientos_Padre',
        ),
        migrations.AlterModelTable(
            name='lineamientogenerado',
            table='Lineamientos_Tipos',
        ),
        migrations.AlterModelTable(
            name='lineamientogeneradofila',
            table='Filas_Lineamientos',
        ),
    ]
