# Generated by Django 6.0.6 on 2026-07-30 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_guideline_options_guideline_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineamiento',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Lineamientos_Padre', 'verbose_name_plural': 'Lineamientos_Padre'},
        ),
        migrations.AlterModelOptions(
            name='lineamientogenerado',
            options={'ordering': ['-version'], 'verbose_name': 'Lineamientos_Tipos', 'verbose_name_plural': 'Lineamientos_Tipos'},
        ),
        migrations.AlterModelOptions(
            name='lineamientogeneradofila',
            options={'ordering': ['orden'], 'verbose_name': 'Filas_Lineamientos', 'verbose_name_plural': 'Filas_Lineamientos'},
        ),
    ]
