# Generated by Django 6.0.6 on 2026-07-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_lineamiento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalizacion',
            name='fecha_cierre_ticket_padre',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre del Ticket Padre'),
        ),
        migrations.AddField(
            model_name='formalizacion',
            name='ticket_padre_cerrado',
            field=models.BooleanField(default=False, help_text='True cuando el cierre automatico del Ticket Padre en Znuny ya se ejecuto tras la ultima firma.', verbose_name='Ticket padre cerrado'),
        ),
    ]
