# Generated by Django 6.0.6 on 2026-07-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_formalizacion_fecha_cierre_ticket_padre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalizacion',
            name='id_lote_firma',
            field=models.CharField(blank=True, default='', help_text='Identificador de lote usado en todas las firmas de esta Formalizacion (firma en cadena).', max_length=100, verbose_name='ID de lote FirmaEC'),
        ),
    ]
