# Generated by Django 6.0.6 on 2026-07-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_formalizacion_id_lote_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalizacion',
            name='total_paginas',
            field=models.PositiveIntegerField(default=0, help_text='Numero de paginas del documento original (fijo mientras exista esta Formalizacion, ya que su contenido depende solo de version_map); se usa para saber cual es la ultima pagina donde FirmaEC debe estampar cada firma.', verbose_name='Total de paginas del PDF'),
        ),
    ]
