# Generated by Django 6.0.6 on 2026-07-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_formalizacion_total_paginas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('revisor', 'Revisor'), ('aprobador', 'Aprobador')], max_length=20, verbose_name='Tipo')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('cargo', models.CharField(max_length=200, verbose_name='Cargo')),
                ('cedula', models.CharField(help_text='Requerida por el WS de FirmaEC para firmar.', max_length=20, verbose_name='Cédula')),
                ('correo', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo electrónico')),
                ('archivo_p12', models.FileField(upload_to='autoridades_p12/', verbose_name='Certificado (.p12)')),
                ('clave_p12', models.CharField(max_length=255, verbose_name='Contraseña del certificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Autoridad',
                'verbose_name_plural': 'Autoridades',
                'ordering': ['tipo', 'nombre_completo'],
            },
        ),
    ]
