# Generated by Django 6.0.6 on 2026-07-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_autoridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoridad',
            name='archivo_p12',
            field=models.FileField(blank=True, null=True, upload_to='autoridades_p12/', verbose_name='Certificado (.p12)'),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='cedula',
            field=models.CharField(blank=True, default='', help_text='Requerida por el WS de FirmaEC para firmar. Si se deja vacia (junto con certificado/contrasena), esta Autoridad solo aparecera como texto en el PDF, sin firma digital automatica.', max_length=20, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='clave_p12',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Contraseña del certificado'),
        ),
    ]
