# Generated by Django 6.0.6 on 2026-08-03 16:18

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_autoridad_archivo_p12_alter_autoridad_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineamientodetalle',
            name='diagrama_personalizado',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.models._ruta_diagrama_personalizado, verbose_name='Diagrama personalizado'),
        ),
    ]
