# Generated by Django 6.0.6 on 2026-08-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_lineamientodetalle_diagrama_personalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineamiento',
            name='id_numerico',
            field=models.CharField(default='', help_text='Identificador manual usado en el codigo del documento (PAS-MLT-{ID}-{Ticket}). Se conserva tal cual se ingreso (ej. con ceros a la izquierda: "001").', max_length=20, verbose_name='ID Numérico del Documento'),
        ),
    ]
