# Generated by Django 6.0.6 on 2026-08-03 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_lineamiento_id_numerico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formalizacion',
            name='fecha_reemplazo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de reemplazo manual'),
        ),
        migrations.AddField(
            model_name='formalizacion',
            name='reemplazado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formalizaciones_reemplazadas', to=settings.AUTH_USER_MODEL, verbose_name='Reemplazado por'),
        ),
        migrations.AddField(
            model_name='formalizacion',
            name='reemplazo_manual',
            field=models.BooleanField(default=False, help_text='True si el PDF fue sustituido a mano por Staff (ej. firma fisica escaneada) en vez de ser generado/firmado por el sistema.', verbose_name='Documento reemplazado manualmente'),
        ),
    ]
