# Generated by Django 6.0.6 on 2026-08-03 19:43

import apps.core.models
import apps.core.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_formalizacion_fecha_reemplazo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoBlob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_original', models.CharField(max_length=255)),
                ('contenido', models.BinaryField()),
                ('tamano', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Archivo (BLOB)',
                'verbose_name_plural': 'Archivos (BLOB)',
            },
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='archivo_p12',
            field=models.FileField(blank=True, null=True, storage=apps.core.storage.PostgresBlobStorage(), upload_to='autoridades_p12/', verbose_name='Certificado (.p12)'),
        ),
        migrations.AlterField(
            model_name='formalizacion',
            name='documento',
            field=models.FileField(storage=apps.core.storage.PostgresBlobStorage(), upload_to='formalizaciones/', verbose_name='PDF consolidado'),
        ),
        migrations.AlterField(
            model_name='lineamientodetalle',
            name='diagrama_personalizado',
            field=models.ImageField(blank=True, null=True, storage=apps.core.storage.PostgresBlobStorage(), upload_to=apps.core.models._ruta_diagrama_personalizado, verbose_name='Diagrama personalizado'),
        ),
    ]
