# Generated by Django 6.0.6 on 2026-08-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_archivoblob_alter_autoridad_archivo_p12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineamientogenerado',
            name='chat_estado',
            field=models.JSONField(blank=True, null=True, verbose_name='Estado del chat (solo software)'),
        ),
        migrations.AddField(
            model_name='lineamientogenerado',
            name='es_borrador',
            field=models.BooleanField(default=False, verbose_name='Es borrador'),
        ),
    ]
