# Generated by Django 6.0.6 on 2026-08-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_lineamientogenerado_chat_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideline',
            name='tipo',
            field=models.CharField(choices=[('SW', 'Software'), ('BDD', 'Base de Datos'), ('INF', 'Infraestructura'), ('ALL', 'Transversal (todos los tipos)')], default='SW', max_length=3, verbose_name='Tipo'),
        ),
    ]
