# Generated by Django 6.0.6 on 2026-09-02 16:36

import apps.core.models
import apps.core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_guideline_consideracion_tecnica'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineamientoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(storage=apps.core.storage.PostgresBlobStorage(), upload_to=apps.core.models._ruta_imagen_lineamiento)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.lineamientodetalle')),
            ],
            options={
                'verbose_name': 'Imagen de Lineamiento',
                'verbose_name_plural': 'Imagenes de Lineamiento',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
