# Generated by Django 6.0.6 on 2026-09-02 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_lineamientoimagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='autoridad',
            name='firma_automatica',
            field=models.BooleanField(default=True, help_text='Si esta activo, el sistema firma solo con las credenciales guardadas arriba apenas le toca su turno (revisor/aprobador), sin intervencion humana. Si se desactiva, el documento queda pendiente aunque haya credenciales guardadas: el usuario vinculado debe entrar y firmarlo el mismo desde su tabla de pendientes, ingresando cedula/password/.p12 (que tambien se guardan aqui).', verbose_name='Firmar automaticamente'),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Si se asigna, este usuario puede iniciar sesion y ver esta Autoridad en su tabla de firmas pendientes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autoridad', to=settings.AUTH_USER_MODEL, verbose_name='Usuario para autofirma'),
        ),
        migrations.CreateModel(
            name='FormalizacionFirmaAutoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmado', models.BooleanField(default=False)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('autoridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas', to='core.autoridad')),
                ('formalizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas_autoridad', to='core.formalizacion')),
            ],
            options={
                'verbose_name': 'Firma de Autoridad',
                'verbose_name_plural': 'Firmas de Autoridad',
                'unique_together': {('formalizacion', 'autoridad')},
            },
        ),
    ]
