# Generated by Django 6.0.6 on 2026-09-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_lineamientogeneradofila_fechas'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineamiento',
            name='asunto',
            field=models.CharField(blank=True, default='', help_text='Asunto tal como aparece en Znuny, obtenido al crear el Lineamiento. Se usa como tooltip donde se muestra el ticket principal.', max_length=255, verbose_name='Asunto del ticket'),
        ),
    ]
