# Generated by Django 6.0.6 on 2026-09-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_lineamiento_asunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineamientogeneradofila',
            name='fecha_texto',
            field=models.CharField(blank=True, default='', help_text='Si el usuario edita la fecha de la fila a mano (tal como aparece en la tabla), se guarda aqui tal cual y prevalece sobre fecha_creacion al mostrarla.', max_length=20, verbose_name='Fecha editada manualmente'),
        ),
    ]
