# Generated by Django 6.0.6 on 2026-09-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_lineamientogeneradofila_fecha_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineamientogeneradofila',
            name='mantener_en_carga_sql',
            field=models.BooleanField(default=False, help_text='Solo aplica a lineamientos de BDD: si esta marcado, la fila no se elimina cuando se carga un nuevo script .sql en la pantalla de generacion.', verbose_name='Mantener al cargar nuevo script SQL'),
        ),
    ]
