# Generated by Django 6.0.6 on 2026-07-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.JSONField(default=list, help_text='Lista de roles: software, bdd, infraestructura', verbose_name='Roles'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, default='software', max_length=20, verbose_name='Rol (legacy)'),
        ),
    ]
